#!/bin/sh
#################################################
#
# The MIT License (MIT)
#
# Copyright (c) 2014-2015 Robert Nevanen
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# he above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#################################################
# Apache 2 vhost adder
# Original made by Droxtor
# Version 1.2.1
# Usage: addsite yourdomaingoeshere.org
#################################################
        if [ `whoami` != root ]; then
            echo Please run this script as root or using sudo
            exit
        fi
	if [ "$1" = "" ]; then
		echo "Example: addsite foobar.org"
		exit
	else
	if [ ! -d /var/www/ ]; then
        echo " == Creating www in /var/"
        mkdir /var/www/
		chmod 0700 /var/www/
        chown -R www-data:www-data /var/www/
	fi
	if [ ! -d /var/www/htdocs/ ]; then
        echo " == Creating htdocs in /var/www/"
        mkdir /var/www/htdocs/
        chown -R www-data:www-data /var/www/htdocs/
	fi
	if [ ! -d /var/www/cgi-bin/ ]; then
        echo " == Creating cgi-bin in /var/www/"
        mkdir /var/www/cgi-bin/
        chown -R www-data:www-data /var/www/cgi-bin/
	fi
	if [ ! -d /var/www/logs/ ]; then
        echo " == Creating logs in /var/www/"
        mkdir /var/www/logs/
        chown -R www-data:www-data /var/www/logs/
	fi
mkdir /var/www/htdocs/$1 /var/www/logs/$1 /var/www/cgi-bin/$1
chown -R www-data:www-data /var/www/htdocs/$1
chown -R www-data:www-data /var/www/logs/$1
chown -R www-data:www-data /var/cgi-bin/$1
if [ -n "$2" ]; then
alias="ServerAlias $2"
fi
echo "<VirtualHost *:80>
       ServerAdmin admin@$1
       ServerName  $1
       $alias
       # Indexes + Directory Root.
       DirectoryIndex index.html index.php
       DocumentRoot /var/www/htdocs/$1/

       # CGI Directory
       ScriptAlias /cgi-bin/ /var/www/cgi-bin/$1/
       <Location /cgi-bin>
               Options +ExecCGI
       </Location>

       # Logfiles
       ErrorLog  /var/www/logs/$1/error.log
       CustomLog /var/www/logs/$1/access.log combined
</VirtualHost>" > /etc/apache2/sites-available/$1.conf
a2ensite $1 >/dev/null 2>&1 &
/etc/init.d/apache2 reload >/dev/null 2>&1 &
fi
echo " == Added $1 succesfully! =="
